<?php

use Illuminate\Database\Seeder;

class ProjectWbsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('pro_wbs')->delete();
        
        \DB::table('pro_wbs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'WBS181010001',
                'name' => 'CONTRACT SIGN',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-12-29',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'WBS181010002',
                'name' => 'APPROVED DESIGN, SPECIFICATION & SHIP DOCUMENT',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2018-12-29',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'WBS181010003',
                'name' => 'Design Drawings & Submission',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 2,
                'status' => 1,
                'planned_deadline' => '2019-01-31',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'WBS181010004',
                'name' => 'Distribution DWG to stakeholder',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 2,
                'status' => 1,
                'planned_deadline' => '2019-05-28',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'WBS181010005',
                'name' => 'Procurement Process',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-04-10',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'WBS181010006',
                'name' => 'Production Process',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-05-21',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'WBS181010007',
                'name' => 'Hull Structure',
                'description' => '',
                'deliverables' => 'Level 2',
                'project_id' => 1,
                'wbs_id' => 6,
                'status' => 1,
                'planned_deadline' => '2019-05-21',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'WBS181010008',
                'name' => 'Bottom',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'WBS181010009',
                'name' => 'Transom',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 8,
                'status' => 1,
                'planned_deadline' => '2019-02-26',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'WBS181010010',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 8,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'WBS181010011',
            'name' => 'Master Block 2 (frame 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 8,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'WBS181010012',
            'name' => 'Block 3 (frame 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 8,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'WBS181010013',
            'name' => 'Block 4 (frame 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 8,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'WBS181010014',
            'name' => 'Block 5 (frame 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 8,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'WBS181010015',
            'name' => 'Block 6 (frame 34-43)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 8,
                'status' => 1,
                'planned_deadline' => '2019-04-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'WBS181010016',
                'name' => 'Tank top',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'WBS181010017',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 16,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'WBS181010018',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 16,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'WBS181010019',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 16,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'WBS181010020',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 16,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'WBS181010036',
            'name' => 'Block 5 (Fr. 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 16,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'WBS181010037',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 16,
                'status' => 1,
                'planned_deadline' => '2019-04-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'WBS181010038',
                'name' => 'Transbulkhead',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'WBS181010039',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 23,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'WBS181010040',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 23,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'WBS181010041',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 23,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'WBS181010042',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 23,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'WBS181010043',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 23,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'WBS181010044',
                'name' => 'Longbulkhead',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'WBS181010046',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 29,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'WBS181010047',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 29,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'WBS181010048',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 29,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'WBS181010049',
            'name' => 'Block 5 (Fr. 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 29,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'WBS181010050',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 29,
                'status' => 1,
                'planned_deadline' => '2019-04-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'WBS181010051',
                'name' => 'Side sheel',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'WBS181010052',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 35,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'WBS181010053',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 35,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'WBS181010054',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 35,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'WBS181010055',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 35,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'WBS181010056',
            'name' => 'Block 5 (Fr. 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 35,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 'WBS181010057',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 35,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 'WBS181010058',
                'name' => 'Main deck',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 'WBS181010059',
            'name' => 'Blok 1 (Fr. 0-15)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 'WBS181010060',
            'name' => 'Master Block 2 (Fr. 15-21)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 'WBS181010061',
            'name' => 'Block 3 (Fr. 21-25)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 'WBS181010062',
            'name' => 'Block 4 (Fr. 25-30)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 'WBS181010063',
            'name' => 'Block 5 (Fr. 30-34)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            47 => 
            array (
                'id' => 48,
                'code' => 'WBS181010064',
            'name' => 'Block 6 (Fr. 34-40)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-17',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 'WBS181010065',
            'name' => 'Block 8 (deck house)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-13',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            49 => 
            array (
                'id' => 50,
                'code' => 'WBS181010066',
            'name' => 'Block 9 (winch house)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-13',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            50 => 
            array (
                'id' => 51,
                'code' => 'WBS181010067',
            'name' => 'Block 7 (skeg)',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 42,
                'status' => 1,
                'planned_deadline' => '2019-04-09',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 'WBS181010068',
                'name' => 'Outfitting Hull',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            52 => 
            array (
                'id' => 53,
                'code' => 'WBS181010069',
                'name' => 'Fabrication',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 52,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 'WBS181010070',
                'name' => 'Installation',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 52,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            54 => 
            array (
                'id' => 55,
                'code' => 'WBS181010071',
                'name' => 'Piping & Safety System',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            55 => 
            array (
                'id' => 56,
                'code' => 'WBS181010072',
                'name' => 'Cargo System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            56 => 
            array (
                'id' => 57,
                'code' => 'WBS181010073',
                'name' => 'General Service & Fire Fighting System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            57 => 
            array (
                'id' => 58,
                'code' => 'WBS181010074',
                'name' => 'Bilge & OWS System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            58 => 
            array (
                'id' => 59,
                'code' => 'WBS181010075',
                'name' => 'Emergency Fire Fighting System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            59 => 
            array (
                'id' => 60,
                'code' => 'WBS181010076',
                'name' => 'Freshwater & Sea Water System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            60 => 
            array (
                'id' => 61,
                'code' => 'WBS181010077',
                'name' => 'Fuel Oil System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            61 => 
            array (
                'id' => 62,
                'code' => 'WBS181010078',
                'name' => 'Holding Tank & Sewage System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            62 => 
            array (
                'id' => 63,
                'code' => 'WBS181010021',
                'name' => 'Air Compressor & Air Pressure',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            63 => 
            array (
                'id' => 64,
                'code' => 'WBS181010079',
                'name' => 'CO2 Fixed System',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 55,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            64 => 
            array (
                'id' => 65,
                'code' => 'WBS181010080',
                'name' => 'Electric & Mechanic',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            65 => 
            array (
                'id' => 66,
                'code' => 'WBS181010081',
                'name' => 'Electric Installation',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 65,
                'status' => 1,
                'planned_deadline' => '2019-04-24',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            66 => 
            array (
                'id' => 67,
                'code' => 'WBS181010082',
                'name' => 'Mechanic Installation',
                'description' => '',
                'deliverables' => 'Level 4',
                'project_id' => 1,
                'wbs_id' => 65,
                'status' => 1,
                'planned_deadline' => '2019-04-06',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            67 => 
            array (
                'id' => 68,
                'code' => 'WBS181010083',
                'name' => 'Coating',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-05-08',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            68 => 
            array (
                'id' => 69,
                'code' => 'WBS181010084',
                'name' => 'Interior and Furniture',
                'description' => '',
                'deliverables' => 'Level 3',
                'project_id' => 1,
                'wbs_id' => 7,
                'status' => 1,
                'planned_deadline' => '2019-05-21',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            69 => 
            array (
                'id' => 70,
                'code' => 'WBS181010085',
                'name' => 'Launching',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-04-27',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            70 => 
            array (
                'id' => 71,
                'code' => 'WBS181010086',
                'name' => 'Testing Commisioning and Familirisasion',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-05-15',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            71 => 
            array (
                'id' => 72,
                'code' => 'WBS181010087',
                'name' => 'DELIVERY',
                'description' => '',
                'deliverables' => 'Level 1',
                'project_id' => 1,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-05-28',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => NULL,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 00:00:00',
                'updated_at' => '2018-12-19 00:00:00',
            ),
            72 => 
            array (
                'id' => 73,
                'code' => 'WBS181020001',
                'name' => 'Dummy - Hull',
                'description' => 'Dummy - Hull',
                'deliverables' => 'Dummy - Hull',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-01-21',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 50.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:27:15',
                'updated_at' => '2018-12-19 09:27:57',
            ),
            73 => 
            array (
                'id' => 74,
                'code' => 'WBS181020002',
                'name' => 'Dummy - Superstructure',
                'description' => 'Dummy - Superstructure',
                'deliverables' => 'Dummy - Superstructure',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-02-23',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 40.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:27:44',
                'updated_at' => '2018-12-19 09:28:31',
            ),
            74 => 
            array (
                'id' => 75,
                'code' => 'WBS181020003',
                'name' => 'Dummy - Outfitting',
                'description' => 'Dummy - Outfitting',
                'deliverables' => 'Dummy - Outfitting',
                'project_id' => 2,
                'wbs_id' => NULL,
                'status' => 1,
                'planned_deadline' => '2019-03-26',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 10.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:28:25',
                'updated_at' => '2018-12-19 09:28:25',
            ),
            75 => 
            array (
                'id' => 76,
                'code' => 'WBS181020004',
                'name' => 'Dummy - Mengelas 1',
                'description' => 'Dummy - Mengelas 1',
                'deliverables' => 'Dummy - Mengelas 1',
                'project_id' => 2,
                'wbs_id' => 73,
                'status' => 1,
                'planned_deadline' => '2019-01-03',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 25.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:29:09',
                'updated_at' => '2018-12-19 09:29:09',
            ),
            76 => 
            array (
                'id' => 77,
                'code' => 'WBS181020005',
                'name' => 'Dummy - Bending 1',
                'description' => 'Dummy - Bending 1',
                'deliverables' => 'Dummy - Bending 1',
                'project_id' => 2,
                'wbs_id' => 73,
                'status' => 1,
                'planned_deadline' => '2019-01-20',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 25.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:29:34',
                'updated_at' => '2018-12-19 09:29:34',
            ),
            77 => 
            array (
                'id' => 78,
                'code' => 'WBS181020006',
                'name' => 'Dummy - Mengelas 2',
                'description' => 'Dummy - Mengelas 2',
                'deliverables' => 'Dummy - Mengelas 2',
                'project_id' => 2,
                'wbs_id' => 74,
                'status' => 1,
                'planned_deadline' => '2019-02-02',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 20.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:30:24',
                'updated_at' => '2018-12-19 09:30:24',
            ),
            78 => 
            array (
                'id' => 79,
                'code' => 'WBS181020007',
                'name' => 'Dummy - Bending 2',
                'description' => 'Dummy - Bending 2',
                'deliverables' => 'Dummy - Bending 2',
                'project_id' => 2,
                'wbs_id' => 74,
                'status' => 1,
                'planned_deadline' => '2019-02-22',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 20.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:30:42',
                'updated_at' => '2018-12-19 09:30:42',
            ),
            79 => 
            array (
                'id' => 80,
                'code' => 'WBS181020008',
                'name' => 'Dummy - Coating',
                'description' => 'Dummy - Coating',
                'deliverables' => 'Dummy - Coating',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-03-05',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:31:28',
                'updated_at' => '2018-12-19 09:31:28',
            ),
            80 => 
            array (
                'id' => 81,
                'code' => 'WBS181020009',
                'name' => 'Dummy - Painting',
                'description' => 'Dummy - Painting',
                'deliverables' => 'Dummy - Painting',
                'project_id' => 2,
                'wbs_id' => 75,
                'status' => 1,
                'planned_deadline' => '2019-03-26',
                'actual_deadline' => NULL,
                'progress' => 0.0,
                'weight' => 5.0,
                'user_id' => 5,
                'branch_id' => 1,
                'process_cost' => NULL,
                'other_cost' => NULL,
                'created_at' => '2018-12-19 09:31:54',
                'updated_at' => '2018-12-19 09:31:54',
            ),
        ));
    }
}
